version: '3'
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    volumes:
      - "wordpress-data:/var/www/localhost/htdocs"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_DATABASE: ${WP_DATABASE}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_MAIL: ${WP_USER_MAIL}

  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - "wordpress-data:/var/www/localhost/htdocs"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dasereno/data/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dasereno/data/wordpress

networks:
  inception:
